name: ci

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto  
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npm install cypress
          $(npm bin)/cypress run

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/videos  # Pode ser ajustado conforme necessário

      - name: Generate Cypress Report
        uses: bahmutov/cypress-gh-action@v2
        with:
          reportDir: cypress/reports/mochareports
